import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Comment from '@/models/comment';
import ViewerConfig from '@/models/viewerConfig';

const gospelComments = [
"Amen! Glory to God for A Special Service 🙏🔥",
  "Watching from Lagos! Dr Daysman is blessing me big time!",
  "This A Special Service na fire 🔥🔥 God dey move!",
  "David Hernandez just prayed and I felt the power of God!",
  "Watching from Nairobi 🇰🇪, this message dey enter body!",
  "I receive healing in Jesus name during this A Special Service!",
  "Thank you Jesus for using Dr Daysman and David Hernandez 🙏",
  "Abuja in the house! Glory to God!",
  "Dr Daysman dey speak life! I feel the anointing!",
  "My spirit is lifted watching this A Special Service!",
  "Hallelujah! Jesus is Lord over my family!",
  "Watching from Accra 🇬🇭, the presence of God strong here!",
  "David Hernandez, man of prayer! God bless you sir!",
  "This word touch my soul 😭🙏",
  "Fire of the Holy Ghost dey burn for my room right now 🔥",
  "Watching from Calabar! Glory to God!",
  "Dr Daysman Oyakhilome you too much for God! 🙌",
  "This message just change my mindset completely!",
  "Thank you Lord, my miracle is here tonight!",
  "God bless A Special Service team 🙏",
  "I tap into this grace from Port Harcourt!",
  "Jesus is alive! Glory to God forever!",
  "Pastor David, I feel the anointing through the screen 🔥",
  "I’m watching from UK 🇬🇧, so blessed by this service!",
  "Holy Ghost power moving strong in this A Special Service!",
  "Omo this message sweet me! God too faithful 🙌",
  "Dr Daysman you’re a blessing to this generation!",
  "I dey watch from Benin City! Gloryyy!",
  "God answer my prayer today! 🙏🔥",
  "David Hernandez preaching with fire 🔥🔥🔥",
  "A Special Service don scatter me! Holy Spirit takeover!",
  "Jesus reigns forever! Hallelujah!",
  "Watching from South Africa 🇿🇦, feeling blessed 🙏",
  "Abeg pray for my mama, she sick 🙏",
  "Pastor David talk am well – faith dey move mountain!",
  "God bless you Dr Daysman for this timely word!",
  "Lagos watching strong 💪 Glory be to God!",
  "A Special Service go long today ooo 😂🔥",
  "I feel peace in my heart. Thank you Jesus!",
  "The Spirit of God dey strong for this program 🙌",
  "Prayer point: Lord restore my business this month 🙏",
  "Watching from Zambia 🇿🇲, I dey enjoy the worship!",
  "Holy Spirit just touched me right now 😭😭😭",
  "Dr Daysman Oyakhilome, your words full of grace!",
  "Pastor David Hernandez, may God increase your anointing!",
  "I believe my testimony is next! 🙌🔥",
  "This worship session carry me go another realm!",
  "Amen amen amen!!! God dey answer prayer!",
  "Watching from Jos! This word heavy!",
  "Na today my breakthrough go happen 🙏🔥",
  "Jesus I thank you for my healing tonight!",
  "This A Special Service sweet pass jollof 😅🔥",
  "God is using Dr Daysman mightily!",
  "I no fit hold my tears 😭😭 Glory to God!",
  "David Hernandez pray again abeg 🔥🔥",
  "Holy Ghost fire everywhere! 🙌",
  "Watching from Warri, na real power we dey see!",
  "This program don touch my family 🙏",
  "Lord please bless my children 🙏🙏",
  "From Enugu watching with faith! Amen!",
  "I receive my miracle job in Jesus name!",
  "Dr Daysman you dey speak rhema today!",
  "A Special Service go viral today by fire 🔥🔥🔥",
  "David Hernandez worship is powerful 🙏",
  "Watching from Canada 🇨🇦, I feel connected!",
  "Jesus is real! Glory to the Lamb of God!",
  "This service don renew my faith 🙌",
  "Prayer request: God give me direction in my life 🙏",
  "The anointing too much on Dr Daysman today!",
  "Watching from Makurdi! God bless the ministers!",
  "Holy Spirit dey move! I dey shake right now 😭🔥",
  "Watching from Ghana, I love this A Special Service!",
  "Lord help me overcome my fears 🙏",
  "My business go blow this year by grace! 🙌",
  "Dr Daysman and David Hernandez, fire combo 🔥🔥🔥",
  "Jesus take control of my life!",
  "Watching from Dubai 🇦🇪, such a mighty word!",
  "I dey cry joy tears 😭😭😭",
  "Holy Spirit power full everywhere tonight!",
  "Lord bless me financially this month 🙏",
  "My faith don rise again! Glory to God!",
  "Dr Daysman preaching deep revelation 🙌",
  "David Hernandez thank you for yielding to God 🙏",
  "Watching from Uyo! Spirit-filled service!",
  "This program na pure fire 🔥🔥🔥",
  "God no dey fail 🙌",
  "Lord please heal my brother 🙏🙏🙏",
  "Watching from Italy 🇮🇹, I’m blessed by A Special Service!",
  "Jesus we exalt your name forever!",
  "Dr Daysman carrying heavy grace!",
  "Holy Ghost dey my room as I watch!",
  "This service make my spirit dance 💃🔥",
  "Pastor David Hernandez is a man of prayer indeed!",
  "Watching from Ibadan, the anointing full ground!",
  "Na only God fit bless like this 🙌",
  "My heart dey full of gratitude 🙏🙏",
  "Prayer request: Lord give me fruit of the womb 🙏😭",
  "The atmosphere is charged with the Spirit of God!",
  "Dr Daysman speak again sir, I dey write notes ✍️",
  "A Special Service go change many lives today!",
  "Glory to Jesus forevermore 🙌🔥",
  "Watching from Kenya 🇰🇪, hallelujah!",
  "Pastor David Hernandez just said it! I believe!",
  "This word dey enter my bone! 🔥🔥🔥",
  "God bless the entire Loveworld family!",
  "Watching with my family, we dey rejoice 🙏",
  "Jesus is doing wonders tonight! Glory!",
  "Na this kind service we need every week 😂🔥",
  "Prayer request: Lord restore my joy 🙏",
  "David Hernandez carry prophetic grace!",
  "Dr Daysman you’re my mentor sir 🙏🔥",
  "The joy of the Lord dey my spirit right now!",
  "Watching from Jos, na heaven we dey like this!",
  "Holy Spirit fire everywhere in this A Special Service!",
  "Jesus you too good o! 🙌🙌🙌",
  "I feel revival in my soul tonight 🔥🔥🔥",
  "Lord please touch my mother in the hospital 🙏😭",
  "Watching from PH, Dr Daysman you too dey try for God!",
  "This worship dey sweet my spirit 🙌🙌🙌",
  "David Hernandez I honor your ministry!",
  "A Special Service changing lives globally! 🌍🔥",
  "Amen! Faith activated! Glory to God!",
  "Thank you Jesus, my testimony is close 🙏🔥",
  "Watching from Abuja! Na power everywhere!",
  "Dr Daysman and Pastor David = heavenly combo 🔥",
  "Holy Ghost dey take control tonight 🙌🙌",
  "Lord use me for your glory 🙏",
  "This A Special Service na blessing upon blessing!",
  "Watching from Owerri! This A Special Service na pure anointing!",
  "Dr Daysman word sweet like honey 🔥🔥",
  "David Hernandez preaching with so much fire! 🙌",
  "Prayer request: Lord bless my marriage 🙏",
  "Holy Spirit dey move, I can feel am here 😭😭",
  "From Ghana 🇬🇭 watching A Special Service live! Glory!",
  "My life no go remain the same after today!",
  "Dr Daysman Oyakhilome carrying kingdom fire 🔥🔥",
  "Jesus take control of my destiny 🙏",
  "David Hernandez your worship sweet die!",
  "Watching from Cameroon 🇨🇲, the presence of God thick!",
  "Prayer request: Lord help me pass my exams 🙏",
  "I dey feel chills! Holy Spirit power full ground 🔥",
  "Abeg pray for my papa, he need healing 🙏😭",
  "A Special Service na real blessing 🙏🙌",
  "Watching from Zambia 🇿🇲, I’m connected spiritually!",
  "Dr Daysman preaching deep revelation 🙌🔥",
  "This worship dey make my eyes tear up 😭😭😭",
  "Prayer request: Lord make my visa come through 🙏",
  "Thank you Jesus for your mercy that never ends!",
  "David Hernandez sound carry power 🔥🔥🔥",
  "From Jos, I dey enjoy every moment of A Special Service!",
  "The Spirit of God no get boundary 🙌🙌",
  "Watching from Ibadan, na supernatural move be this!",
  "Dr Daysman words dey hit my soul direct 🔥",
  "David Hernandez singing like angel 😭🙌",
  "Prayer request: Lord make my business pick up this week 🙏",
  "Abuja watching loud and clear! Glory to God!",
  "Holy Ghost fire just fill my room! 🔥🔥🔥",
  "Jesus be praised forevermore!",
  "A Special Service na real encounter 🙏🙌",
  "Dr Daysman, man full of revelation!",
  "Pastor David Hernandez carry Spirit of prayer! 🙌",
  "Watching from Warri! This service choke 🔥🔥🔥",
  "Omo this A Special Service sweet like heaven on earth!",
  "Thank you Jesus, my heart dey full of joy!",
  "Prayer request: Lord help me forgive those who hurt me 🙏",
  "Holy Spirit, I surrender all to you!",
  "Watching from Bayelsa, glory to the Most High!",
  "Dr Daysman dey talk rhema wey go change my mindset 🙌",
  "David Hernandez dey flow with Spirit! Fire everywhere 🔥🔥",
  "I no fit sit still again 😭 Holy Ghost dey move!",
  "Prayer request: Lord give me new job 🙏",
  "Watching from Cape Town 🇿🇦, the presence of God sweet!",
  "This service na pure revival 🙌🔥",
  "Dr Daysman and David Hernandez, God bless una!",
  "I dey cry, I feel Jesus for my room 😭😭😭",
  "Watching from Kenya 🇰🇪, I’m blessed beyond words!",
  "Prayer request: Lord bless my hands’ work 🙏",
  "Holy Spirit dey manifest live and direct 🔥🔥🔥",
  "David Hernandez prayer just shift atmosphere!",
  "Dr Daysman’s message na pure revelation from heaven!",
  "Watching from Port Harcourt, na serious anointing today!",
  "I tap into this grace in Jesus name 🙏🔥",
  "Prayer request: Lord bless me with fruit of the womb 🙏😭",
  "Na glory upon glory for this program!",
  "A Special Service don ignite my spirit 🔥🔥🔥",
  "Watching from Kano! Hallelujah to the Lamb!",
  "Dr Daysman Oyakhilome, thank you for blessing us 🙏",
  "David Hernandez ministry too powerful 🔥",
  "Prayer request: Lord, give me strength to continue 🙏",
  "Holy Ghost fire dey scatter my worries 🔥🔥",
  "This worship session na pure heaven!",
  "Watching from Enugu! Jesus dey move!",
  "Dr Daysman talk say faith no dey fail — I believe! 🙌",
  "David Hernandez pray make my life turn around 🙏🔥",
  "Prayer request: Lord heal my heart and restore my peace 🙏",
  "Watching from Jos, God dey truly move!",
  "Na my testimony time be this! 🙌🔥",
  "Dr Daysman preaching with heavenly boldness!",
  "A Special Service don carry me enter new level 🙌",
  "Lord thank you for using Pastor David mightily!",
  "Watching from Gombe! Fire full everywhere 🔥🔥🔥",
  "Holy Spirit fill me afresh 🙏🔥",
  "Prayer request: Lord protect my family 🙏🙏🙏",
  "David Hernandez ministry dey bless me every time!",
  "Dr Daysman you be vessel of light 🔥",
  "Watching from Lagos, the worship sweet die 😭😭",
  "I believe my healing don happen tonight 🙌🔥",
  "Na this kind revival we need everyday!",
  "Prayer request: Lord open doors for me 🙏",
  "Dr Daysman and David Hernandez dey shake the kingdom!",
  "Watching from Abuja, glory to the King of Kings!",
  "This A Special Service na global movement 🙌🔥",
  "Prayer request: Lord bless me with wisdom 🙏",
  "Jesus I give you praise forevermore!",
  "Holy Ghost dey carry my body 😭😭😭",
  "Watching from Kano, my life don change today!",
  "Dr Daysman, your message dey sink deep 🙌🔥",
  "David Hernandez prophetic words too accurate!",
  "Prayer request: Lord, give me breakthrough 🙏🔥",
  "This worship no be ordinary o!",
  "Watching from Benin City! Na joy everywhere 🙌🔥",
  "My life don turn around from today onward!",
  "Thank you Jesus, A Special Service na blessing galore!",
  "Holy Spirit fill my home with peace 🙏🔥",
  "Watching from Calabar, na tears of joy dey my eyes 😭😭😭",
  "Dr Daysman and Pastor David dey operate with same Spirit!",
  "Prayer request: Lord bless my husband 🙏",
  "Jesus reigns forever! 🙌🙌🙌",
  "Watching from Ghana 🇬🇭, God too faithful!",
  "Na spiritual power I dey see for this livestream 🔥🔥🔥",
  "Dr Daysman message sweet like honey!",
  "Prayer request: Lord help me grow in faith 🙏",
  "Watching from Tanzania 🇹🇿, I’m lifted spiritually!",
  "Pastor David dey release heavy anointing!",
  "I dey shout Amen like say I dey inside hall 😂🔥",
  "A Special Service carry serious presence of God!",
  "Watching from Owerri! Na joy dey flood my heart!",
  "Prayer request: Lord restore my finances 🙏",
  "Dr Daysman dey talk straight from Spirit of God!",
  "David Hernandez your message touch my spirit 🙌🔥",
  "Watching from Onitsha! Jesus na Lord forever!",
  "The anointing strong well well tonight 🔥🔥🔥",
  "Holy Spirit I’m yours forever 🙏",
  "Prayer request: Lord bless me with good job 🙏",
  "Dr Daysman preaching like firebrand tonight!",
  "Watching from Liberia 🇱🇷, glory to God!",
  "David Hernandez you dey channel pure power 🙌🔥",
  "Jesus my heart full of gratitude tonight!",
  "Prayer request: Lord bring peace to Nigeria 🙏🇳🇬",
  "Watching from Malawi 🇲🇼, such a powerful ministration!",
  "A Special Service dey sweet my soul 🙏🔥",
  "Dr Daysman message full of grace and power!",
  "David Hernandez carry Holy Ghost heavy!",
  "Watching from Jos, I dey dance for joy 💃🙌",
  "Prayer request: Lord restore my lost opportunities 🙏",
  "The Spirit of God dey here indeed!",
  "Dr Daysman na true man of God 🙌🔥",
  "David Hernandez you inspire me to pray more 🙏🔥",
  "Watching from Abuja, this service na blessing galore!",
  "Prayer request: Lord make my dreams come true 🙏",
  "This A Special Service no go end empty! 🙌🔥",
  "Jesus thank you for this divine encounter!",
  "Na power, na glory, na Holy Ghost everywhere!",
  "Watching from Ekiti! A Special Service na my new start!",
  "Prayer request: Lord give me wisdom to serve you 🙏",
  "Dr Daysman and David Hernandez, God bless your ministries!",
  "Watching from Asaba! A Special Service dey sweet me 🔥🔥",
  "Dr Daysman Oyakhilome, you carry grace wey dey change lives 🙏",
  "David Hernandez fire too much today 🙌🔥",
  "Prayer request: Lord make my rent issue settle this week 🙏",
  "Na glory time be this! Holy Ghost full everywhere 😭🔥",
  "Watching from Ghana 🇬🇭, my life don change!",
  "Dr Daysman word today enter my heart deep 🙌",
  "Jesus you too faithful abeg! 🙏",
  "Pastor David worship make me cry 😭😭😭",
  "A Special Service na divine visitation indeed 🔥",
  "Watching from Abuja with my whole family! Glory!",
  "Prayer request: Lord bless my children with wisdom 🙏",
  "David Hernandez voice carry Holy Ghost fire 🔥🔥🔥",
  "I dey shake, presence of God strong for my room 🙌🔥",
  "Dr Daysman, your revelation dey blow my mind!",
  "Watching from USA 🇺🇸, connected in spirit 🙏🔥",
  "Prayer request: Lord open my womb this year 🙏😭",
  "Holy Spirit just touch me, I feel peace 😭😭",
  "This service na turning point for my destiny 🙌🔥",
  "Dr Daysman you dey pour Spirit water today 🔥🔥",
  "Watching from Owerri! Glory to Jesus!",
  "Prayer request: Lord help me stop anxiety 🙏",
  "David Hernandez you be real worshipper 🙌🔥",
  "This worship na heaven on earth experience 😭😭",
  "Holy Ghost no dey joke tonight o! 🔥🔥🔥",
  "Watching from Port Harcourt! Na revival we dey see!",
  "Dr Daysman Oyakhilome, thank you for yielding to God 🙏",
  "Prayer request: Lord bless my business clients 🙏",
  "A Special Service no be ordinary program!",
  "David Hernandez prophetic prayers carry weight 🙌🔥",
  "Watching from Delta State! God dey do wonders!",
  "Na tears of joy dey my eyes 😭😭",
  "Prayer request: Lord bless my fiancé 🙏",
  "Dr Daysman dey operate in pure wisdom tonight!",
  "Watching from Zambia 🇿🇲, fire everywhere!",
  "Jesus, I surrender all! 🙌🙌",
  "Prayer request: Lord heal my leg 🙏😭",
  "David Hernandez you inspire me to draw near to God 🙏🔥",
  "Watching from Benue! A Special Service na serious encounter!",
  "Na Holy Spirit vibes full my living room 😭🔥",
  "Prayer request: Lord bless my academics 🙏",
  "Dr Daysman message today na rhema from heaven 🙌🔥",
  "Watching from Kenya 🇰🇪, feeling the move of God!",
  "David Hernandez flow in Spirit steady steady 🔥🔥",
  "Prayer request: Lord send me destiny helpers 🙏",
  "Jesus thank you for this A Special Service 🙌🔥",
  "Watching from London 🇬🇧, I dey rejoice in the Spirit!",
  "Holy Ghost dey do overtime tonight 😂🔥🔥",
  "Dr Daysman word dey heal my heart 🙏",
  "Prayer request: Lord settle my family matter 🙏",
  "David Hernandez worship na pure oil of heaven 🙌🔥",
  "Watching from Cameroon 🇨🇲, full of joy and fire!",
  "This service na pure Spirit demonstration!",
  "Dr Daysman talk deep truth today 🔥🔥",
  "Prayer request: Lord give me patience and grace 🙏",
  "Jesus be glorified forevermore!",
  "Watching from Ghana 🇬🇭, I feel peace all over 🙌",
  "Na this kind service wey dey renew faith 🔥🔥🔥",
  "Prayer request: Lord bless my ministry 🙏",
  "David Hernandez you dey preach love and truth 🙌🔥",
  "Watching from Jos! Na revival I dey witness!",
  "Dr Daysman, your smile carry anointing 😂🔥",
  "Prayer request: Lord bless my relationship 🙏",
  "Holy Spirit dey touch lives through this broadcast 🙌🔥",
  "Watching from Kano, I no wan miss one word!",
  "David Hernandez you carry heavy grace 🔥🔥🔥",
  "Dr Daysman Oyakhilome I celebrate grace sir 🙏",
  "Prayer request: Lord, make me a vessel of honor 🙌",
  "Watching from Bayelsa, Holy Ghost full my house!",
  "Na joy overflow everywhere 🔥🙌",
  "Jesus thank you for divine favor 🙏🔥",
  "Watching from Uyo, A Special Service na blessing galore!",
  "Prayer request: Lord lift me from depression 🙏😭",
  "Dr Daysman dey speak direct from throne room 🙌🔥",
  "David Hernandez your worship open heaven 🔥🔥",
  "Watching from Italy 🇮🇹, this service sweet my soul 🙌",
  "Holy Spirit fill me afresh again 🙏🔥",
  "Prayer request: Lord bless my mama with healing 🙏😭",
  "A Special Service no fit end without my miracle!",
  "Watching from Sokoto! I dey shout Amen loud 🔥🔥",
  "Dr Daysman I dey thank God for your life 🙌",
  "David Hernandez thank you for yielding to Spirit 🙏",
  "Prayer request: Lord favor me for job interview 🙏",
  "Holy Ghost dey move like wind 😭😭😭",
  "Watching from Accra 🇬🇭, this service choke 🔥🔥",
  "Jesus, I give you all the praise and glory 🙌🙌",
  "Prayer request: Lord connect me to right people 🙏",
  "Dr Daysman, God go bless you more sir 🙏🔥",
  "David Hernandez, may God strengthen you always 🙌",
  "Watching from PH, I dey cry joy tears 😭😭😭",
  "This word na rhema for me today 🙌🔥",
  "Prayer request: Lord give me spiritual growth 🙏",
  "Holy Ghost fire everywhere for A Special Service 🔥🔥🔥",
  "Watching from Abuja, I no go ever forget this service!",
  "Dr Daysman na true example of humility 🙏",
  "David Hernandez, your prayer change my heart 😭🙌",
  "Prayer request: Lord make me strong in faith 🙏",
  "Na Holy Ghost revival we dey see live and direct 🔥🔥🔥",
  "Watching from Jos! Hallelujah!",
  "Jesus, my redeemer forever 🙌🔥",
  "Prayer request: Lord settle my debts 🙏",
  "Dr Daysman Oyakhilome, thank you for your obedience 🙏🔥",
  "David Hernandez ministry dey inspire youth 🙌",
  "Watching from Enugu! Na heaven on earth tonight!",
  "This A Special Service go remain in history 🙌🔥",
  "Prayer request: Lord give me boldness to preach 🙏",
  "Na power wey no get limit dey this place 🔥🔥🔥",
  "Watching from Lagos, the anointing too strong!",
  "Dr Daysman word today restore my hope 🙌",
  "David Hernandez Holy Ghost carrier 🔥🔥🔥",
  "Prayer request: Lord heal my father 🙏",
  "Holy Spirit thank you for peace in my heart 🙌",
  "Watching from Benin City, na tears of joy full my eyes 😭",
  "This worship na heaven preview 🔥🙌🔥",
  "Dr Daysman you too dey flow with Spirit! Glory!",
  "Prayer request: Lord give me breakthrough in exams 🙏",
  "David Hernandez, your words dey build my faith 🙌🔥",
  "Watching from Akwa Ibom, I no fit hold my excitement!",
  "Jesus, na you be everything for me 🙏🔥",
  "Prayer request: Lord remove shame from my life 🙏😭",
  "A Special Service na turning point indeed 🙌🔥",
  "Watching from Nairobi 🇰🇪, glory to God!",
  "Dr Daysman you be true servant of God 🙏🔥",
  "David Hernandez ministry dey carry global fire 🔥🔥🔥",
  "Prayer request: Lord bless my family with peace 🙏",
  "Holy Ghost dey move strong in this atmosphere 🙌🔥",
  "Watching from Abuja! A Special Service na wonder!",
  "Na supernatural shift dey happen right now 🔥🔥",
  "Dr Daysman, your words sweet like honey 🙏🔥",
  "David Hernandez I dey feel your passion for God 🙌🔥",
  "Prayer request: Lord give me wisdom for my career 🙏",
  "Watching from Kaduna! Na power we dey witness o!",
  "Jesus, I love you forever 🙏🙌",
  "Dr Daysman Oyakhilome and David Hernandez, world changers 🔥🔥🔥",
  "This A Special Service go carry me enter new season 🙌🔥",
  "Prayer request: Lord make my testimony loud this month 🙏🔥",
];

const nigerianNames = [
  "Adewale", "Chidinma", "Oluwaseun", "Chukwuemeka", "Blessing", "Emmanuel",
  "Adeola", "Chiamaka", "Tunde", "Ngozi", "Segun", "Amaka", "Yemi", "Ifeoma",
  "Kunle", "Chioma", "Femi", "Nneka", "Bolu", "Adaeze", "Wale", "Ebere",
  "Tolu", "Chinyere", "Dare", "Oge", "Biodun", "Amarachi", "Kemi", "Obiageli",
  "Seyi", "Uchechi", "Lanre", "Nkechi", "Gbenga", "Chinenye", "Sola", "Ijeoma",
  "Dele", "Adaora", "Toyin", "Chinonso", "Bayo", "Ifunanya", "Yinka", "Nnamdi",
  "Funmi", "Chukwudi", "Jide", "Nkemdilim", "Tobi", "Ezinne", "Shola", "Uchenna",
  "Kola", "Chidera", "Deji", "Ngozika", "Niyi", "Chiamaka", "Tayo", "Adaugo",
  "Ibrahim", "Fatima", "Musa", "Aisha", "Usman", "Zainab", "Sani", "Hauwa",
  "Abdullahi", "Hadiza", "Aliyu", "Maryam", "Ahmed", "Safiya", "Abubakar", "Aishatu",
  "John", "Grace", "David", "Faith", "Michael", "Joy", "Daniel", "Peace",
  "Samuel", "Mercy", "Joseph", "Hope", "Peter", "Love", "Paul", "Patience",
  "James", "Favour", "Abraham", "Gift", "Moses", "Glory", "Isaac", "Precious",
  "Joshua", "Victory", "Stephen", "Divine", "Matthew", "Goodness", "Mark", "Praise",
];

const locations = [
  "Lagos", "Abuja", "Jos", "Kaduna", "Port Harcourt", "Enugu", "Ibadan", "Kano",
  "Warri", "Benin City", "Calabar", "Owerri", "Uyo", "Abeokuta", "Ilorin", "Maiduguri",
  "Sokoto", "Zaria", "Makurdi", "CEF Jos", "Nairobi", "Accra", "Johannesburg",
  "Kampala", "Cape Town", "Dar es Salaam", "Kigali", "Lusaka", "Addis Ababa", "Harare",
  "Abuja FCT", "Lekki", "Victoria Island", "Ikeja", "Surulere", "Yaba",
];

export async function POST(req: NextRequest) {
  try {
    const { streamId } = await req.json();

    if (!streamId) {
      return NextResponse.json(
        { error: 'streamId is required' },
        { status: 400 }
      );
    }

    await connectDB();

    // Check if simulated comments are enabled
    const config = await ViewerConfig.findOne({ streamId: 'global' });
    if (config && !config.commentsActive) {
      // Comments are paused - silently return success without creating comment
      return NextResponse.json({
        success: true,
        paused: true,
        message: 'Simulated comments are currently paused',
      });
    }

    // Clean up old comments to prevent database bloat
    // Keep only the latest 500 comments per stream
    const commentCount = await Comment.countDocuments({ streamId });
    if (commentCount > 500) {
      // Get the oldest comments to delete
      const commentsToDelete = await Comment.find({ streamId })
        .sort({ createdAt: 1 }) // Oldest first
        .limit(commentCount - 500) // Delete excess comments
        .select('_id')
        .lean();
      
      const idsToDelete = commentsToDelete.map(c => c._id);
      await Comment.deleteMany({ _id: { $in: idsToDelete } });
      console.log(`🗑️ Cleaned up ${idsToDelete.length} old comments for stream ${streamId}`);
    }

    // Generate random comment and username
    const randomComment = gospelComments[Math.floor(Math.random() * gospelComments.length)];
    
    // Generate username - just the name, sometimes with numbers
    const randomName = nigerianNames[Math.floor(Math.random() * nigerianNames.length)];
    const addNumber = Math.random() < 0.3; // 30% chance to add number
    const randomUsername = addNumber ? `${randomName}${Math.floor(Math.random() * 1000)}` : randomName;

    // Create simulated comment in database
    const comment = await Comment.create({
      streamId: streamId,
      userId: `simulated_${Date.now()}_${Math.random()}`,
      username: randomUsername,
      text: randomComment,
    });

    return NextResponse.json({
      success: true,
      comment: {
        _id: comment._id,
        streamId: comment.streamId,
        userId: comment.userId,
        username: comment.username,
        text: comment.text,
        createdAt: comment.createdAt,
      },
    });
  } catch (error) {
    console.error('Error creating simulated comment:', error);
    return NextResponse.json(
      { error: 'Failed to create simulated comment' },
      { status: 500 }
    );
  }
}
